blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/mt26691/ai-templates-cli#readme
    about: Check out our comprehensive documentation
  - name: 🚀 Quick Start Guide
    url: https://github.com/mt26691/ai-templates-cli#quick-setup
    about: Get started with AI Templates CLI in minutes